--
-- PostgreSQL database dump
--

\restrict Ov5PRS5MsJyoXsiRbIrVGHf6ydScKxazdreZRiz21lWDPFEqLhaMReGUerA3phs

-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 16.11 (Debian 16.11-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    email character varying(254) NOT NULL,
    name character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    is_superuser boolean NOT NULL,
    role character varying(20) NOT NULL,
    restaurant_id bigint,
    phone character varying(15),
    profile_image character varying(255)
);


ALTER TABLE public.accounts_user OWNER TO postgres;

--
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user_groups (
    id integer NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_user_groups OWNER TO postgres;

--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user_user_permissions (
    id integer NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_user_user_permissions OWNER TO postgres;

--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id integer NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_clockedschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_clockedschedule (
    id integer NOT NULL,
    clocked_time timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_clockedschedule OWNER TO postgres;

--
-- Name: django_celery_beat_clockedschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_clockedschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_clockedschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_crontabschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_crontabschedule (
    id integer NOT NULL,
    minute character varying(240) NOT NULL,
    hour character varying(96) NOT NULL,
    day_of_week character varying(64) NOT NULL,
    day_of_month character varying(124) NOT NULL,
    month_of_year character varying(64) NOT NULL,
    timezone character varying(63) NOT NULL
);


ALTER TABLE public.django_celery_beat_crontabschedule OWNER TO postgres;

--
-- Name: django_celery_beat_crontabschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_crontabschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_crontabschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_intervalschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_intervalschedule (
    id integer NOT NULL,
    every integer NOT NULL,
    period character varying(24) NOT NULL
);


ALTER TABLE public.django_celery_beat_intervalschedule OWNER TO postgres;

--
-- Name: django_celery_beat_intervalschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_intervalschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_intervalschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictask; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_periodictask (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    task character varying(200) NOT NULL,
    args text NOT NULL,
    kwargs text NOT NULL,
    queue character varying(200),
    exchange character varying(200),
    routing_key character varying(200),
    expires timestamp with time zone,
    enabled boolean NOT NULL,
    last_run_at timestamp with time zone,
    total_run_count integer NOT NULL,
    date_changed timestamp with time zone NOT NULL,
    description text NOT NULL,
    crontab_id integer,
    interval_id integer,
    solar_id integer,
    one_off boolean NOT NULL,
    start_time timestamp with time zone,
    priority integer,
    headers text NOT NULL,
    clocked_id integer,
    expire_seconds integer,
    CONSTRAINT django_celery_beat_periodictask_expire_seconds_check CHECK ((expire_seconds >= 0)),
    CONSTRAINT django_celery_beat_periodictask_priority_check CHECK ((priority >= 0)),
    CONSTRAINT django_celery_beat_periodictask_total_run_count_check CHECK ((total_run_count >= 0))
);


ALTER TABLE public.django_celery_beat_periodictask OWNER TO postgres;

--
-- Name: django_celery_beat_periodictask_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_periodictask ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_periodictask_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_periodictasks (
    ident smallint NOT NULL,
    last_update timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_periodictasks OWNER TO postgres;

--
-- Name: django_celery_beat_solarschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_solarschedule (
    id integer NOT NULL,
    event character varying(24) NOT NULL,
    latitude numeric(9,6) NOT NULL,
    longitude numeric(9,6) NOT NULL
);


ALTER TABLE public.django_celery_beat_solarschedule OWNER TO postgres;

--
-- Name: django_celery_beat_solarschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_solarschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_solarschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id integer NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: menu_menucategory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.menu_menucategory (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    display_order integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    restaurant_id bigint NOT NULL,
    CONSTRAINT menu_menucategory_display_order_check CHECK ((display_order >= 0))
);


ALTER TABLE public.menu_menucategory OWNER TO postgres;

--
-- Name: menu_menucategory_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.menu_menucategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_menucategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menu_menuitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.menu_menuitem (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    description character varying(500) NOT NULL,
    price numeric(10,2) NOT NULL,
    is_veg boolean NOT NULL,
    is_available boolean NOT NULL,
    is_active boolean NOT NULL,
    display_order integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    category_id bigint NOT NULL,
    restaurant_id bigint NOT NULL,
    image character varying(255),
    CONSTRAINT menu_menuitem_display_order_check CHECK ((display_order >= 0))
);


ALTER TABLE public.menu_menuitem OWNER TO postgres;

--
-- Name: menu_menuitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.menu_menuitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_menuitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_order (
    id bigint NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    restaurant_id bigint NOT NULL,
    table_id uuid NOT NULL,
    status character varying(20) NOT NULL
);


ALTER TABLE public.orders_order OWNER TO postgres;

--
-- Name: orders_order_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_orderitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_orderitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    price numeric(10,2) NOT NULL,
    menu_item_id bigint,
    order_id bigint NOT NULL,
    CONSTRAINT orders_orderitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.orders_orderitem OWNER TO postgres;

--
-- Name: orders_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: restaurants_restaurant; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restaurants_restaurant (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    owner_id bigint NOT NULL,
    address character varying(255),
    city character varying(100),
    country character varying(100),
    email character varying(254),
    phone character varying(15),
    restaurant_type character varying(20),
    state character varying(100),
    logo character varying(255),
    primary_color character varying(7),
    secondary_color character varying(7),
    theme character varying(20) NOT NULL,
    is_onboarding_completed boolean NOT NULL
);


ALTER TABLE public.restaurants_restaurant OWNER TO postgres;

--
-- Name: restaurants_restaurant_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.restaurants_restaurant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_restaurant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: restaurants_table; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restaurants_table (
    id uuid NOT NULL,
    table_number integer NOT NULL,
    qr_code character varying(100),
    created_at timestamp with time zone NOT NULL,
    restaurant_id bigint NOT NULL,
    CONSTRAINT restaurants_table_table_number_check CHECK ((table_number >= 0))
);


ALTER TABLE public.restaurants_table OWNER TO postgres;

--
-- Data for Name: accounts_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user (id, password, last_login, email, name, is_active, is_staff, created_at, is_superuser, role, restaurant_id, phone, profile_image) FROM stdin;
1	pbkdf2_sha256$870000$pKmgCSy0MZB00RBmwv9Es8$KrGiXqO7VjyTNKlMmh/Pt/MWYBFL/gorycgFbNGEMvA=	\N	jota@gmail.com	jota	t	f	2026-03-02 11:20:31.967994+00	f	RESTAURANT_ADMIN	1	\N	\N
2	pbkdf2_sha256$870000$t3QyvhcU1g7VLDLRP41XMt$ET6xAqI1m8iEaTYZ0z5TFQi+R+8667LOOXhLhy2l9CY=	\N	roshan@gmail.com	roshan	t	f	2026-05-21 08:10:22.350645+00	f	RESTAURANT_ADMIN	2	\N	\N
\.


--
-- Data for Name: accounts_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: accounts_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add crontab	6	add_crontabschedule
22	Can change crontab	6	change_crontabschedule
23	Can delete crontab	6	delete_crontabschedule
24	Can view crontab	6	view_crontabschedule
25	Can add interval	7	add_intervalschedule
26	Can change interval	7	change_intervalschedule
27	Can delete interval	7	delete_intervalschedule
28	Can view interval	7	view_intervalschedule
29	Can add periodic task	8	add_periodictask
30	Can change periodic task	8	change_periodictask
31	Can delete periodic task	8	delete_periodictask
32	Can view periodic task	8	view_periodictask
33	Can add periodic task track	9	add_periodictasks
34	Can change periodic task track	9	change_periodictasks
35	Can delete periodic task track	9	delete_periodictasks
36	Can view periodic task track	9	view_periodictasks
37	Can add solar event	10	add_solarschedule
38	Can change solar event	10	change_solarschedule
39	Can delete solar event	10	delete_solarschedule
40	Can view solar event	10	view_solarschedule
41	Can add clocked	11	add_clockedschedule
42	Can change clocked	11	change_clockedschedule
43	Can delete clocked	11	delete_clockedschedule
44	Can view clocked	11	view_clockedschedule
45	Can add user	12	add_user
46	Can change user	12	change_user
47	Can delete user	12	delete_user
48	Can view user	12	view_user
49	Can add restaurant	13	add_restaurant
50	Can change restaurant	13	change_restaurant
51	Can delete restaurant	13	delete_restaurant
52	Can view restaurant	13	view_restaurant
53	Can add table	14	add_table
54	Can change table	14	change_table
55	Can delete table	14	delete_table
56	Can view table	14	view_table
57	Can add menu category	15	add_menucategory
58	Can change menu category	15	change_menucategory
59	Can delete menu category	15	delete_menucategory
60	Can view menu category	15	view_menucategory
61	Can add menu item	16	add_menuitem
62	Can change menu item	16	change_menuitem
63	Can delete menu item	16	delete_menuitem
64	Can view menu item	16	view_menuitem
65	Can add order	17	add_order
66	Can change order	17	change_order
67	Can delete order	17	delete_order
68	Can view order	17	view_order
69	Can add order item	18	add_orderitem
70	Can change order item	18	change_orderitem
71	Can delete order item	18	delete_orderitem
72	Can view order item	18	view_orderitem
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_clockedschedule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_beat_clockedschedule (id, clocked_time) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_crontabschedule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_beat_crontabschedule (id, minute, hour, day_of_week, day_of_month, month_of_year, timezone) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_intervalschedule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_beat_intervalschedule (id, every, period) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_periodictask; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_beat_periodictask (id, name, task, args, kwargs, queue, exchange, routing_key, expires, enabled, last_run_at, total_run_count, date_changed, description, crontab_id, interval_id, solar_id, one_off, start_time, priority, headers, clocked_id, expire_seconds) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_periodictasks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_beat_periodictasks (ident, last_update) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_solarschedule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_beat_solarschedule (id, event, latitude, longitude) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	django_celery_beat	crontabschedule
7	django_celery_beat	intervalschedule
8	django_celery_beat	periodictask
9	django_celery_beat	periodictasks
10	django_celery_beat	solarschedule
11	django_celery_beat	clockedschedule
12	accounts	user
13	restaurants	restaurant
14	restaurants	table
15	menu	menucategory
16	menu	menuitem
17	orders	order
18	orders	orderitem
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	accounts	0001_initial	2026-03-02 11:10:55.496064+00
2	restaurants	0001_initial	2026-03-02 11:10:55.583001+00
3	contenttypes	0001_initial	2026-03-02 11:10:55.617797+00
4	contenttypes	0002_remove_content_type_name	2026-03-02 11:10:55.644405+00
5	auth	0001_initial	2026-03-02 11:10:55.819218+00
6	auth	0002_alter_permission_name_max_length	2026-03-02 11:10:55.831656+00
7	auth	0003_alter_user_email_max_length	2026-03-02 11:10:55.850765+00
8	auth	0004_alter_user_username_opts	2026-03-02 11:10:55.872695+00
9	auth	0005_alter_user_last_login_null	2026-03-02 11:10:55.929963+00
10	auth	0006_require_contenttypes_0002	2026-03-02 11:10:55.936376+00
11	auth	0007_alter_validators_add_error_messages	2026-03-02 11:10:55.949584+00
12	auth	0008_alter_user_username_max_length	2026-03-02 11:10:55.999161+00
13	auth	0009_alter_user_last_name_max_length	2026-03-02 11:10:56.016822+00
14	auth	0010_alter_group_name_max_length	2026-03-02 11:10:56.072551+00
15	auth	0011_update_proxy_permissions	2026-03-02 11:10:56.094114+00
16	auth	0012_alter_user_first_name_max_length	2026-03-02 11:10:56.111148+00
17	accounts	0002_user_groups_user_is_superuser_user_user_permissions	2026-03-02 11:10:56.28926+00
18	accounts	0003_user_role	2026-03-02 11:10:56.35294+00
19	accounts	0004_user_restaurant	2026-03-02 11:10:56.418893+00
20	accounts	0005_user_phone	2026-03-02 11:10:56.436132+00
21	accounts	0006_user_profile_image	2026-03-02 11:10:56.492394+00
22	admin	0001_initial	2026-03-02 11:10:56.609072+00
23	admin	0002_logentry_remove_auto_add	2026-03-02 11:10:56.637287+00
24	admin	0003_logentry_add_action_flag_choices	2026-03-02 11:10:56.702906+00
25	django_celery_beat	0001_initial	2026-03-02 11:10:56.930087+00
26	django_celery_beat	0002_auto_20161118_0346	2026-03-02 11:10:57.05483+00
27	django_celery_beat	0003_auto_20161209_0049	2026-03-02 11:10:57.088364+00
28	django_celery_beat	0004_auto_20170221_0000	2026-03-02 11:10:57.104362+00
29	django_celery_beat	0005_add_solarschedule_events_choices	2026-03-02 11:10:57.11866+00
30	django_celery_beat	0006_auto_20180322_0932	2026-03-02 11:10:57.219742+00
31	django_celery_beat	0007_auto_20180521_0826	2026-03-02 11:10:57.262744+00
32	django_celery_beat	0008_auto_20180914_1922	2026-03-02 11:10:57.307767+00
33	django_celery_beat	0006_auto_20180210_1226	2026-03-02 11:10:57.34722+00
34	django_celery_beat	0006_periodictask_priority	2026-03-02 11:10:57.394473+00
35	django_celery_beat	0009_periodictask_headers	2026-03-02 11:10:57.518143+00
36	django_celery_beat	0010_auto_20190429_0326	2026-03-02 11:10:57.900966+00
37	django_celery_beat	0011_auto_20190508_0153	2026-03-02 11:10:57.983768+00
38	django_celery_beat	0012_periodictask_expire_seconds	2026-03-02 11:10:58.018977+00
39	django_celery_beat	0013_auto_20200609_0727	2026-03-02 11:10:58.064487+00
40	django_celery_beat	0014_remove_clockedschedule_enabled	2026-03-02 11:10:58.076607+00
41	django_celery_beat	0015_edit_solarschedule_events_choices	2026-03-02 11:10:58.119712+00
42	django_celery_beat	0016_alter_crontabschedule_timezone	2026-03-02 11:10:58.172548+00
43	django_celery_beat	0017_alter_crontabschedule_month_of_year	2026-03-02 11:10:58.21368+00
44	django_celery_beat	0018_improve_crontab_helptext	2026-03-02 11:10:58.235277+00
45	django_celery_beat	0019_alter_periodictasks_options	2026-03-02 11:10:58.26749+00
46	restaurants	0002_restaurant_address_restaurant_city_and_more	2026-03-02 11:10:58.402534+00
47	restaurants	0003_restaurant_logo_restaurant_primary_color_and_more	2026-03-02 11:10:58.445403+00
48	restaurants	0004_table	2026-03-02 11:10:58.529726+00
49	menu	0001_initial	2026-03-02 11:10:58.595086+00
50	menu	0002_menuitem	2026-03-02 11:10:58.704257+00
51	menu	0003_menuitem_image	2026-03-02 11:10:58.720232+00
52	orders	0001_initial	2026-03-02 11:10:58.913408+00
53	orders	0002_order_status_alter_order_total_amount	2026-03-02 11:10:58.949024+00
54	restaurants	0005_restaurant_is_onboarding_completed	2026-03-02 11:10:58.979246+00
55	restaurants	0006_alter_restaurant_logo	2026-03-02 11:10:59.024803+00
56	restaurants	0007_alter_restaurant_logo	2026-03-02 11:10:59.064021+00
57	sessions	0001_initial	2026-03-02 11:10:59.140037+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: menu_menucategory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.menu_menucategory (id, name, is_active, display_order, created_at, updated_at, restaurant_id) FROM stdin;
1	Starters	t	1	2026-03-02 11:22:00.166528+00	2026-03-02 11:22:00.166542+00	1
2	Main Course	t	1	2026-03-02 11:22:08.784924+00	2026-03-02 11:22:08.784937+00	1
3	Drinks	t	1	2026-03-02 11:22:14.180075+00	2026-03-02 11:22:14.180094+00	1
4	Deserts	t	1	2026-03-02 11:22:25.997041+00	2026-03-02 11:22:25.997055+00	1
5	Hot	t	1	2026-03-02 11:22:32.853035+00	2026-03-02 11:22:32.853052+00	1
6	Snacks	t	1	2026-05-21 08:17:07.237375+00	2026-05-21 08:17:07.237424+00	2
7	Juices	t	1	2026-05-21 08:17:18.406666+00	2026-05-21 08:17:18.406683+00	2
8	Scoops	t	1	2026-05-21 08:17:28.527793+00	2026-05-21 08:17:28.527808+00	2
\.


--
-- Data for Name: menu_menuitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.menu_menuitem (id, name, description, price, is_veg, is_available, is_active, display_order, created_at, category_id, restaurant_id, image) FROM stdin;
1	Soup	Hot and tasty	110.00	t	t	t	1	2026-03-02 11:23:17.956404+00	1	1	image/upload/v1772450594/lrht4temc0kzrglkgfka.jpg
2	Pizza	Yummy	340.00	f	t	t	1	2026-03-02 11:23:53.696319+00	2	1	image/upload/v1772450629/uosgmqtgmjwbjrqaxdrs.jpg
3	Burger	Delicious	150.00	f	t	t	1	2026-03-02 11:24:22.444587+00	2	1	image/upload/v1772450658/kzduixdunpzqeb4wdmb1.jpg
4	Chocolate	sweet	70.00	f	t	t	1	2026-03-02 11:25:14.793525+00	4	1	image/upload/v1772450709/u7qt3yk0h3firxebpipu.jpg
5	Coffee	hot and milky	30.00	f	t	t	1	2026-03-02 11:26:06.286748+00	5	1	image/upload/v1772450761/ot18il9geap4bfixo5en.jpg
6	Mango Juice	Cold and refresh	80.00	f	t	t	1	2026-03-02 11:26:48.40912+00	3	1	image/upload/v1772450804/fnx0hisonxetvas2b3km.png
7	Strawberry juice	Tasty	80.00	f	t	t	1	2026-05-21 08:18:27.925639+00	7	2	image/upload/v1779351506/zkxfuscktajqwaznt2oi.jpg
8	Chicken Pupps	Crunchy	40.00	f	t	t	2	2026-05-21 08:19:24.656724+00	6	2	image/upload/v1779351562/xsxp43lrw6xeyxt3lw1n.jpg
9	Chocolate Scoop	Cold and chill	29.94	f	t	t	1	2026-05-21 08:20:23.060392+00	8	2	image/upload/v1779351620/xr5uawrnewwamiwsandk.jpg
10	Egg Pupps	Yummy	20.00	t	t	t	3	2026-05-21 08:21:17.851929+00	6	2	image/upload/v1779351675/gsbdojamtaffkvsbbtn7.jpg
11	Pizza	Delicious	120.00	f	t	t	1	2026-05-21 08:22:11.586897+00	6	2	image/upload/v1779351729/ub6jjzcidffiqqx8kmu2.jpg
\.


--
-- Data for Name: orders_order; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders_order (id, total_amount, is_active, created_at, restaurant_id, table_id, status) FROM stdin;
6	140.00	f	2026-03-02 12:02:20.208764+00	1	92b2c292-aa60-45fa-9741-d122d77948c2	SERVED
7	140.00	f	2026-03-02 14:55:28.95735+00	1	92b2c292-aa60-45fa-9741-d122d77948c2	SERVED
5	80.00	f	2026-03-02 11:54:43.780393+00	1	92b2c292-aa60-45fa-9741-d122d77948c2	SERVED
10	630.00	f	2026-03-02 15:59:29.29512+00	1	92b2c292-aa60-45fa-9741-d122d77948c2	SERVED
9	390.00	f	2026-03-02 15:59:11.639077+00	1	92b2c292-aa60-45fa-9741-d122d77948c2	SERVED
12	1010.00	f	2026-03-02 16:33:47.851585+00	1	92b2c292-aa60-45fa-9741-d122d77948c2	SERVED
13	1130.00	f	2026-03-02 16:46:12.602493+00	1	92b2c292-aa60-45fa-9741-d122d77948c2	SERVED
11	450.00	f	2026-03-02 16:32:07.325956+00	1	92b2c292-aa60-45fa-9741-d122d77948c2	SERVED
14	780.00	f	2026-03-02 18:11:38.183201+00	1	92b2c292-aa60-45fa-9741-d122d77948c2	SERVED
8	900.00	f	2026-03-02 15:58:48.85045+00	1	92b2c292-aa60-45fa-9741-d122d77948c2	SERVED
4	90.00	f	2026-03-02 11:51:17.831233+00	1	92b2c292-aa60-45fa-9741-d122d77948c2	SERVED
3	30.00	f	2026-03-02 11:48:04.470983+00	1	92b2c292-aa60-45fa-9741-d122d77948c2	SERVED
2	150.00	f	2026-03-02 11:30:24.817698+00	1	92b2c292-aa60-45fa-9741-d122d77948c2	SERVED
1	110.00	f	2026-03-02 11:28:54.760411+00	1	92b2c292-aa60-45fa-9741-d122d77948c2	SERVED
15	1340.00	f	2026-03-02 18:28:07.035167+00	1	92b2c292-aa60-45fa-9741-d122d77948c2	SERVED
16	2440.00	t	2026-03-02 18:29:18.776973+00	1	92b2c292-aa60-45fa-9741-d122d77948c2	PLACED
17	80.00	f	2026-03-02 18:41:30.290327+00	1	92b2c292-aa60-45fa-9741-d122d77948c2	SERVED
18	80.00	f	2026-05-21 18:12:32.52314+00	2	4213b447-01a8-4909-b29a-0512ac13bb79	SERVED
19	149.94	f	2026-05-21 18:15:07.550432+00	2	4213b447-01a8-4909-b29a-0512ac13bb79	SERVED
20	189.94	f	2026-05-22 09:00:37.868353+00	2	4213b447-01a8-4909-b29a-0512ac13bb79	SERVED
\.


--
-- Data for Name: orders_orderitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders_orderitem (id, quantity, price, menu_item_id, order_id) FROM stdin;
1	1	110.00	1	1
2	1	150.00	3	2
3	1	30.00	5	3
4	3	30.00	5	4
5	1	80.00	6	5
6	2	70.00	4	6
7	2	70.00	4	7
8	1	70.00	4	8
9	1	150.00	3	8
10	2	340.00	2	8
11	1	110.00	1	9
12	4	70.00	4	9
13	1	80.00	6	10
14	1	30.00	5	10
15	1	70.00	4	10
16	3	150.00	3	10
17	1	110.00	1	11
18	1	340.00	2	11
19	3	110.00	1	12
20	2	340.00	2	12
21	1	110.00	1	13
22	3	340.00	2	13
23	1	110.00	1	14
24	1	340.00	2	14
25	1	150.00	3	14
26	1	70.00	4	14
27	1	30.00	5	14
28	1	80.00	6	14
29	1	110.00	1	15
30	2	340.00	2	15
31	2	150.00	3	15
32	2	70.00	4	15
33	1	30.00	5	15
34	1	80.00	6	15
35	1	110.00	1	16
36	5	340.00	2	16
37	3	150.00	3	16
38	1	70.00	4	16
39	1	30.00	5	16
40	1	80.00	6	16
41	1	80.00	6	17
42	1	80.00	7	18
43	1	29.94	9	19
44	1	120.00	11	19
45	2	80.00	7	20
46	1	29.94	9	20
\.


--
-- Data for Name: restaurants_restaurant; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.restaurants_restaurant (id, name, is_active, created_at, owner_id, address, city, country, email, phone, restaurant_type, state, logo, primary_color, secondary_color, theme, is_onboarding_completed) FROM stdin;
1	JotaLAnd	t	2026-03-02 11:20:32.311729+00	1	Kolamban House Perincholam Mnannarkkad	Palakkad,Mannarkkad	India	jota@gmail.com	917736295327	CAFE	Kerala	image/upload/v1772450472/caqmdrsakl1dmjqcipz9.jpg	#2bee6c	#0d1b12	light	t
2	kh	t	2026-05-21 08:10:22.612286+00	2	123 Culinary Ave	New York	New	shahabas123@gmail.com	9876543210	CAFE	NY	image/upload/v1779351172/hpcbnvmdqycht8pdfzle.jpg	#1a1e1b	#0fc24e	light	t
\.


--
-- Data for Name: restaurants_table; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.restaurants_table (id, table_number, qr_code, created_at, restaurant_id) FROM stdin;
92b2c292-aa60-45fa-9741-d122d77948c2	1	table_qrCodes/table_1_Frv319y.png	2026-03-02 11:21:19.945985+00	1
b8f19d8c-32e0-425c-af73-ff31a39a6c4d	2	table_qrCodes/table_2_nm1jPwZ.png	2026-03-02 11:21:20.16697+00	1
265e84b4-75c8-441a-ac99-f5622e4d0b16	3	table_qrCodes/table_3_UQvjTUA.png	2026-03-02 11:21:20.214393+00	1
b4addfdb-b508-45b3-9f0c-cdd84c113438	4	table_qrCodes/table_4_3IXgvn2.png	2026-03-02 11:21:20.269731+00	1
175aec18-c33b-4bd9-a71c-1a2b33c164e6	5	table_qrCodes/table_5_MxsilGG.png	2026-03-02 11:21:20.336755+00	1
7f51a521-fdea-4721-ab32-89b141eb0ea5	6	table_qrCodes/table_6_pxIasKf.png	2026-03-02 11:21:20.451997+00	1
d08066ea-6b06-4bea-8479-cdc01fbfc82d	7	table_qrCodes/table_7_4VCroG3.png	2026-03-02 11:21:20.567526+00	1
1ed1deae-5203-42ec-a948-5f88157197d9	8	table_qrCodes/table_8_i21WzS5.png	2026-03-02 11:21:20.680855+00	1
e3194941-0202-4a4a-a4f8-0adbd7fbfc49	9	table_qrCodes/table_9_p05dFgQ.png	2026-03-02 11:21:20.789071+00	1
d9ececcc-3b8e-411c-abe8-fba269acf51b	10	table_qrCodes/table_10_2JsUo7i.png	2026-03-02 11:21:20.901651+00	1
ac6f1a4c-8be8-49f2-a111-b97cd2447115	1	table_qrCodes/table_1_24a8TMV.png	2026-05-21 08:13:07.082884+00	2
4213b447-01a8-4909-b29a-0512ac13bb79	2	table_qrCodes/table_2_lBDX7gX.png	2026-05-21 08:13:08.168485+00	2
0aa81eb0-9661-4a1b-a5ef-54a56f9ffa8c	3	table_qrCodes/table_3_9shr9CE.png	2026-05-21 08:13:08.294548+00	2
5baf0fa0-fd1d-4cf6-8443-96448910fe0a	4	table_qrCodes/table_4_IXfPHPB.png	2026-05-21 08:13:08.645261+00	2
2cbc9367-f75f-42b3-994a-e82cd402ade8	5	table_qrCodes/table_5_GGFNwo4.png	2026-05-21 08:13:08.810648+00	2
59f6e832-7106-42c2-8b93-e9e9edb39338	6	table_qrCodes/table_6_bRgBOv7.png	2026-05-21 08:13:09.159245+00	2
e1b3233b-117f-4de7-9e1c-cf153dac2fb0	7	table_qrCodes/table_7_47hyP71.png	2026-05-21 08:13:10.136371+00	2
d9c49a84-d835-4a15-a7b2-3235b8fe6f8c	8	table_qrCodes/table_8_aofBTp8.png	2026-05-21 08:13:10.348205+00	2
\.


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_groups_id_seq', 1, false);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_id_seq', 2, true);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 72, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_celery_beat_clockedschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_beat_clockedschedule_id_seq', 1, false);


--
-- Name: django_celery_beat_crontabschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_beat_crontabschedule_id_seq', 1, false);


--
-- Name: django_celery_beat_intervalschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_beat_intervalschedule_id_seq', 1, false);


--
-- Name: django_celery_beat_periodictask_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_beat_periodictask_id_seq', 1, false);


--
-- Name: django_celery_beat_solarschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_beat_solarschedule_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 18, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 57, true);


--
-- Name: menu_menucategory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.menu_menucategory_id_seq', 8, true);


--
-- Name: menu_menuitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.menu_menuitem_id_seq', 11, true);


--
-- Name: orders_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_order_id_seq', 20, true);


--
-- Name: orders_orderitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_orderitem_id_seq', 46, true);


--
-- Name: restaurants_restaurant_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.restaurants_restaurant_id_seq', 2, true);


--
-- Name: accounts_user accounts_user_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_email_key UNIQUE (email);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_clockedschedule django_celery_beat_clockedschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_clockedschedule
    ADD CONSTRAINT django_celery_beat_clockedschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_crontabschedule django_celery_beat_crontabschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_crontabschedule
    ADD CONSTRAINT django_celery_beat_crontabschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_intervalschedule django_celery_beat_intervalschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_intervalschedule
    ADD CONSTRAINT django_celery_beat_intervalschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_name_key UNIQUE (name);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictasks django_celery_beat_periodictasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictasks
    ADD CONSTRAINT django_celery_beat_periodictasks_pkey PRIMARY KEY (ident);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq UNIQUE (event, latitude, longitude);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solarschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solarschedule_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: menu_menucategory menu_menucategory_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu_menucategory
    ADD CONSTRAINT menu_menucategory_pkey PRIMARY KEY (id);


--
-- Name: menu_menucategory menu_menucategory_restaurant_id_name_eab7ad9c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu_menucategory
    ADD CONSTRAINT menu_menucategory_restaurant_id_name_eab7ad9c_uniq UNIQUE (restaurant_id, name);


--
-- Name: menu_menuitem menu_menuitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu_menuitem
    ADD CONSTRAINT menu_menuitem_pkey PRIMARY KEY (id);


--
-- Name: menu_menuitem menu_menuitem_restaurant_id_category_id_name_1a1d0fea_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu_menuitem
    ADD CONSTRAINT menu_menuitem_restaurant_id_category_id_name_1a1d0fea_uniq UNIQUE (restaurant_id, category_id, name);


--
-- Name: orders_order orders_order_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_pkey PRIMARY KEY (id);


--
-- Name: orders_orderitem orders_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_pkey PRIMARY KEY (id);


--
-- Name: restaurants_restaurant restaurants_restaurant_owner_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_restaurant
    ADD CONSTRAINT restaurants_restaurant_owner_id_key UNIQUE (owner_id);


--
-- Name: restaurants_restaurant restaurants_restaurant_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_restaurant
    ADD CONSTRAINT restaurants_restaurant_pkey PRIMARY KEY (id);


--
-- Name: restaurants_table restaurants_table_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_table
    ADD CONSTRAINT restaurants_table_pkey PRIMARY KEY (id);


--
-- Name: restaurants_table restaurants_table_restaurant_id_table_number_7d05f2a8_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_table
    ADD CONSTRAINT restaurants_table_restaurant_id_table_number_7d05f2a8_uniq UNIQUE (restaurant_id, table_number);


--
-- Name: accounts_user_email_b2644a56_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_email_b2644a56_like ON public.accounts_user USING btree (email varchar_pattern_ops);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_restaurant_id_67ec68f1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_restaurant_id_67ec68f1 ON public.accounts_user USING btree (restaurant_id);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_celery_beat_periodictask_clocked_id_47a69f82; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_clocked_id_47a69f82 ON public.django_celery_beat_periodictask USING btree (clocked_id);


--
-- Name: django_celery_beat_periodictask_crontab_id_d3cba168; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_crontab_id_d3cba168 ON public.django_celery_beat_periodictask USING btree (crontab_id);


--
-- Name: django_celery_beat_periodictask_interval_id_a8ca27da; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_interval_id_a8ca27da ON public.django_celery_beat_periodictask USING btree (interval_id);


--
-- Name: django_celery_beat_periodictask_name_265a36b7_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_name_265a36b7_like ON public.django_celery_beat_periodictask USING btree (name varchar_pattern_ops);


--
-- Name: django_celery_beat_periodictask_solar_id_a87ce72c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_solar_id_a87ce72c ON public.django_celery_beat_periodictask USING btree (solar_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: menu_menucategory_restaurant_id_4cdb2a55; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX menu_menucategory_restaurant_id_4cdb2a55 ON public.menu_menucategory USING btree (restaurant_id);


--
-- Name: menu_menuitem_category_id_af353a3b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX menu_menuitem_category_id_af353a3b ON public.menu_menuitem USING btree (category_id);


--
-- Name: menu_menuitem_restaurant_id_aeed3392; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX menu_menuitem_restaurant_id_aeed3392 ON public.menu_menuitem USING btree (restaurant_id);


--
-- Name: orders_order_restaurant_id_a38fbfc0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_order_restaurant_id_a38fbfc0 ON public.orders_order USING btree (restaurant_id);


--
-- Name: orders_order_table_id_14015bc1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_order_table_id_14015bc1 ON public.orders_order USING btree (table_id);


--
-- Name: orders_orderitem_menu_item_id_72e84539; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_orderitem_menu_item_id_72e84539 ON public.orders_orderitem USING btree (menu_item_id);


--
-- Name: orders_orderitem_order_id_fe61a34d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_orderitem_order_id_fe61a34d ON public.orders_orderitem USING btree (order_id);


--
-- Name: restaurants_table_restaurant_id_0a055aef; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX restaurants_table_restaurant_id_0a055aef ON public.restaurants_table USING btree (restaurant_id);


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user accounts_user_restaurant_id_67ec68f1_fk_restauran; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_restaurant_id_67ec68f1_fk_restauran FOREIGN KEY (restaurant_id) REFERENCES public.restaurants_restaurant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_clocked_id_47a69f82_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_clocked_id_47a69f82_fk_django_ce FOREIGN KEY (clocked_id) REFERENCES public.django_celery_beat_clockedschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_crontab_id_d3cba168_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_crontab_id_d3cba168_fk_django_ce FOREIGN KEY (crontab_id) REFERENCES public.django_celery_beat_crontabschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_interval_id_a8ca27da_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_interval_id_a8ca27da_fk_django_ce FOREIGN KEY (interval_id) REFERENCES public.django_celery_beat_intervalschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_solar_id_a87ce72c_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_solar_id_a87ce72c_fk_django_ce FOREIGN KEY (solar_id) REFERENCES public.django_celery_beat_solarschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: menu_menucategory menu_menucategory_restaurant_id_4cdb2a55_fk_restauran; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu_menucategory
    ADD CONSTRAINT menu_menucategory_restaurant_id_4cdb2a55_fk_restauran FOREIGN KEY (restaurant_id) REFERENCES public.restaurants_restaurant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: menu_menuitem menu_menuitem_category_id_af353a3b_fk_menu_menucategory_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu_menuitem
    ADD CONSTRAINT menu_menuitem_category_id_af353a3b_fk_menu_menucategory_id FOREIGN KEY (category_id) REFERENCES public.menu_menucategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: menu_menuitem menu_menuitem_restaurant_id_aeed3392_fk_restauran; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu_menuitem
    ADD CONSTRAINT menu_menuitem_restaurant_id_aeed3392_fk_restauran FOREIGN KEY (restaurant_id) REFERENCES public.restaurants_restaurant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_order orders_order_restaurant_id_a38fbfc0_fk_restauran; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_restaurant_id_a38fbfc0_fk_restauran FOREIGN KEY (restaurant_id) REFERENCES public.restaurants_restaurant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_order orders_order_table_id_14015bc1_fk_restaurants_table_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_table_id_14015bc1_fk_restaurants_table_id FOREIGN KEY (table_id) REFERENCES public.restaurants_table(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderitem orders_orderitem_menu_item_id_72e84539_fk_menu_menuitem_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_menu_item_id_72e84539_fk_menu_menuitem_id FOREIGN KEY (menu_item_id) REFERENCES public.menu_menuitem(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderitem orders_orderitem_order_id_fe61a34d_fk_orders_order_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_order_id_fe61a34d_fk_orders_order_id FOREIGN KEY (order_id) REFERENCES public.orders_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: restaurants_restaurant restaurants_restaurant_owner_id_9dd1f260_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_restaurant
    ADD CONSTRAINT restaurants_restaurant_owner_id_9dd1f260_fk_accounts_user_id FOREIGN KEY (owner_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: restaurants_table restaurants_table_restaurant_id_0a055aef_fk_restauran; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants_table
    ADD CONSTRAINT restaurants_table_restaurant_id_0a055aef_fk_restauran FOREIGN KEY (restaurant_id) REFERENCES public.restaurants_restaurant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict Ov5PRS5MsJyoXsiRbIrVGHf6ydScKxazdreZRiz21lWDPFEqLhaMReGUerA3phs

