# Generated by Django 6.0.1 on 2026-01-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="restaurant_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CASUAL", "Casual Dining"),
                    ("FINE", "Fine Dining"),
                    ("FAST", "Fast Food"),
                    ("CAFE", "Cafe / Bakery"),
                    ("BAR", "Bar / Pub"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
