# Generated by Django 6.0.1 on 2026-01-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_restaurant_address_restaurant_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="restaurant_logos/"
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="primary_color",
            field=models.CharField(
                blank=True, help_text="hex color like #0EA5E9", max_length=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="secondary_color",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="theme",
            field=models.CharField(
                choices=[("light", "light"), ("dark", "dark")],
                default="light",
                max_length=20,
            ),
        ),
    ]
