# Generated by Django 6.0.1 on 2026-01-21 08:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_restaurant_logo_restaurant_primary_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("table_number", models.PositiveIntegerField()),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="table_qrCodes/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "unique_together": {("restaurant", "table_number")},
            },
        ),
    ]
