# Generated by Django 6.0.1 on 2026-01-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="is_onboarding_completed",
            field=models.BooleanField(default=False),
        ),
    ]
