# Generated by Django 6.0.1 on 2026-02-03 09:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0006_alter_restaurant_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="logo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="logo/"
            ),
        ),
    ]
