# Generated by Django 5.1.7 on 2026-06-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0007_alter_restaurant_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="manual_code",
            field=models.CharField(
                blank=True, editable=False, max_length=6, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
