# Generated by Django 5.1.7 on 2026-06-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0008_table_manual_code_alter_restaurant_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="manual_code",
            field=models.CharField(
                blank=True, editable=False, max_length=6, null=True, unique=True
            ),
        ),
    ]
