# Generated by Django 6.0.1 on 2026-01-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_groups_user_is_superuser_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPERADMIN", "Super Admin"),
                    ("RESTAURANT_ADMIN", "Restaurant Admin"),
                    ("KITCHEN_STAFF", "Kitchen Staff"),
                    ("WAITER", "Waiter"),
                ],
                default="RESTAURANT_ADMIN",
                max_length=20,
            ),
        ),
    ]
