# Generated by Django 6.0.1 on 2026-02-05 06:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="profile"
            ),
        ),
    ]
